### ISSUE TITLE
Is it possible to obtain the download address through an API request?

### ISSUE THREAD

**Issue by edmondsket** [RohanDebroy/ytdl-web#1]
Is it possible to obtain the download address through an API request?

**Comment by RohanDebroy** [comment]
Yes you can. All you have to do is make a request to the following endpoint `/api/info` with a query parameter `url=your video url`. It returns a json response with everything that you will need.

I would also suggest you to clone the repo and deploy your own server.

**Comment by edmondsket** [comment]
> Yes you can. All you have to do is make a request to the following endpoint `/api/info` with a query parameter `url=your video url`. It returns a json response with everything that you will need.
> 
> I would also suggest you to clone the repo and deploy your own server.

thank you! I have already deployed my own one
